// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/meters#COR

static const uint32_t dsp_descriptor_id = 10;
static const uint32_t gui_descriptor_id = 0;
static const char *plugin_human_id = "Stereo Phase-Correlation Meter";

const struct LV2Port ports[6] = {
  { "unused", CONTROL_IN, 0.000000},
  { "inL", AUDIO_IN, nan},
  { "outL", AUDIO_OUT, nan},
  { "levelL", CONTROL_OUT, nan},
  { "inR", AUDIO_IN, nan},
  { "outR", AUDIO_OUT, nan},
};

static const uint32_t nports_total=6;
static const uint32_t nports_audio_in=2;
static const uint32_t nports_audio_out=2;
static const uint32_t nports_midi_in=0;
static const uint32_t nports_midi_out=0;
static const uint32_t nports_atom_in=0;
static const uint32_t nports_atom_out=0;
static const uint32_t nports_ctrl=2;
static const uint32_t nports_ctrl_in=1;
static const uint32_t nports_ctrl_out=1;
static const uint32_t min_atom_bufsiz=1024;
static const bool     send_time_info=false;
