// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/meters#EBUr128

static const uint32_t dsp_descriptor_id = 11;
static const uint32_t gui_descriptor_id = 0;
static const char *plugin_human_id = "EBU R128 Meter";

const struct LV2Port ports[6] = {
  { "control", ATOM_IN, nan},
  { "notify", ATOM_OUT, nan},
  { "inL", AUDIO_IN, nan},
  { "outL", AUDIO_OUT, nan},
  { "inR", AUDIO_IN, nan},
  { "outR", AUDIO_OUT, nan},
};

static const uint32_t nports_total=6;
static const uint32_t nports_audio_in=2;
static const uint32_t nports_audio_out=2;
static const uint32_t nports_midi_in=0;
static const uint32_t nports_midi_out=0;
static const uint32_t nports_atom_in=1;
static const uint32_t nports_atom_out=1;
static const uint32_t nports_ctrl=0;
static const uint32_t nports_ctrl_in=0;
static const uint32_t nports_ctrl_out=0;
static const uint32_t min_atom_bufsiz=8192;
static const bool     send_time_info=true;
