// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/meters#phasewheel

extern const LV2_Descriptor* lv2_descriptor(uint32_t index);
extern const LV2UI_Descriptor* lv2ui_phasewheel(uint32_t index);

static const RtkLv2Description _plugin_phasewheel = {
	&lv2_descriptor,
	&lv2ui_phasewheel
	, 46 // uint32_t dsp_descriptor_id
	, 0 // uint32_t gui_descriptor_id
	, "Phase/Frequency Wheel" // const char *plugin_human_id
	, (struct LV2Port[])
	{
		{ "control", ATOM_IN, nan},
		{ "notify", ATOM_OUT, nan},
		{ "in1", AUDIO_IN, nan},
		{ "out1", AUDIO_OUT, nan},
		{ "in2", AUDIO_IN, nan},
		{ "out2", AUDIO_OUT, nan},
		{ "phase", CONTROL_OUT, nan},
		{ "gain", CONTROL_IN, 20.000000},
		{ "cutoff", CONTROL_IN, -50.000000},
		{ "fftsize", CONTROL_IN, 2048.000000},
		{ "band", CONTROL_IN, 1.000000},
		{ "normalize", CONTROL_IN, 0.000000},
		{ "persistence", CONTROL_IN, 33.000000},
	}
	, 13 // uint32_t nports_total
	, 2 // uint32_t nports_audio_in
	, 2 // uint32_t nports_audio_out
	, 0 // uint32_t nports_midi_in
	, 0 // uint32_t nports_midi_out
	, 1 // uint32_t nports_atom_in
	, 1 // uint32_t nports_atom_out
	, 7 // uint32_t nports_ctrl
	, 6 // uint32_t nports_ctrl_in
	, 1 // uint32_t nports_ctrl_out
	, 65888 // uint32_t min_atom_bufsiz
	, false // bool send_time_info
};

#ifdef X42_PLUGIN_STRUCT
#undef X42_PLUGIN_STRUCT
#endif
#define X42_PLUGIN_STRUCT _plugin_phasewheel
