// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/meters#SigDistHist

static const uint32_t dsp_descriptor_id = 58;
static const uint32_t gui_descriptor_id = 0;
static const char *plugin_human_id = "Signal Distribution Histogram";

const struct LV2Port ports[4] = {
  { "control", ATOM_IN, nan},
  { "notify", ATOM_OUT, nan},
  { "in", AUDIO_IN, nan},
  { "out", AUDIO_OUT, nan},
};

static const uint32_t nports_total=4;
static const uint32_t nports_audio_in=1;
static const uint32_t nports_audio_out=1;
static const uint32_t nports_midi_in=0;
static const uint32_t nports_midi_out=0;
static const uint32_t nports_atom_in=1;
static const uint32_t nports_atom_out=1;
static const uint32_t nports_ctrl=0;
static const uint32_t nports_ctrl_in=0;
static const uint32_t nports_ctrl_out=0;
static const uint32_t min_atom_bufsiz=8192;
static const bool     send_time_info=true;
