// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/meters#stereoscope

static const uint32_t dsp_descriptor_id = 48;
static const uint32_t gui_descriptor_id = 0;
static const char *plugin_human_id = "Stereo/Frequency Scope";

const struct LV2Port ports[9] = {
  { "control", ATOM_IN, nan},
  { "notify", ATOM_OUT, nan},
  { "in1", AUDIO_IN, nan},
  { "out1", AUDIO_OUT, nan},
  { "in2", AUDIO_IN, nan},
  { "out2", AUDIO_OUT, nan},
  { "fftsize", CONTROL_IN, 2048.000000},
  { "band", CONTROL_IN, 1.000000},
  { "persistence", CONTROL_IN, 50.000000},
};

static const uint32_t nports_total=9;
static const uint32_t nports_audio_in=2;
static const uint32_t nports_audio_out=2;
static const uint32_t nports_midi_in=0;
static const uint32_t nports_midi_out=0;
static const uint32_t nports_atom_in=1;
static const uint32_t nports_atom_out=1;
static const uint32_t nports_ctrl=3;
static const uint32_t nports_ctrl_in=3;
static const uint32_t nports_ctrl_out=0;
static const uint32_t min_atom_bufsiz=65888;
static const bool     send_time_info=false;
