// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/meters#surround8

extern const LV2_Descriptor* lv2_descriptor(uint32_t index);
extern const LV2UI_Descriptor* lv2ui_surmeter(uint32_t index);

static const RtkLv2Description _plugin_surmeter = {
	&lv2_descriptor,
	&lv2ui_surmeter
	, 64 // uint32_t dsp_descriptor_id
	, 0 // uint32_t gui_descriptor_id
	, "Surround Level 8 " // const char *plugin_human_id
	, (const struct LV2Port[25])
	{
		{ "ref", CONTROL_IN, -4.000000, -4.000000, 4.000000, "ui notification"},
		{ "in1", AUDIO_IN, nan, nan, nan, "In1"},
		{ "out1", AUDIO_OUT, nan, nan, nan, "Out1"},
		{ "level1", CONTROL_OUT, nan, 0.000000, 1.000000, "Level1"},
		{ "in2", AUDIO_IN, nan, nan, nan, "In2"},
		{ "out2", AUDIO_OUT, nan, nan, nan, "Out2"},
		{ "level2", CONTROL_OUT, nan, 0.000000, 1.000000, "Level2"},
		{ "in3", AUDIO_IN, nan, nan, nan, "In3"},
		{ "out3", AUDIO_OUT, nan, nan, nan, "Out3"},
		{ "level3", CONTROL_OUT, nan, 0.000000, 1.000000, "Level3"},
		{ "in4", AUDIO_IN, nan, nan, nan, "In4"},
		{ "out4", AUDIO_OUT, nan, nan, nan, "Out4"},
		{ "level4", CONTROL_OUT, nan, 0.000000, 1.000000, "Level4"},
		{ "in5", AUDIO_IN, nan, nan, nan, "In5"},
		{ "out5", AUDIO_OUT, nan, nan, nan, "Out5"},
		{ "level5", CONTROL_OUT, nan, 0.000000, 1.000000, "Level5"},
		{ "in6", AUDIO_IN, nan, nan, nan, "In6"},
		{ "out6", AUDIO_OUT, nan, nan, nan, "Out6"},
		{ "level6", CONTROL_OUT, nan, 0.000000, 1.000000, "Level6"},
		{ "in7", AUDIO_IN, nan, nan, nan, "In7"},
		{ "out7", AUDIO_OUT, nan, nan, nan, "Out7"},
		{ "level7", CONTROL_OUT, nan, 0.000000, 1.000000, "Level7"},
		{ "in8", AUDIO_IN, nan, nan, nan, "In8"},
		{ "out8", AUDIO_OUT, nan, nan, nan, "Out8"},
		{ "level8", CONTROL_OUT, nan, 0.000000, 1.000000, "Level8"},
	}
	, 25 // uint32_t nports_total
	, 8 // uint32_t nports_audio_in
	, 8 // uint32_t nports_audio_out
	, 0 // uint32_t nports_midi_in
	, 0 // uint32_t nports_midi_out
	, 0 // uint32_t nports_atom_in
	, 0 // uint32_t nports_atom_out
	, 9 // uint32_t nports_ctrl
	, 1 // uint32_t nports_ctrl_in
	, 8 // uint32_t nports_ctrl_out
	, 8192 // uint32_t min_atom_bufsiz
	, false // bool send_time_info
};


#ifdef X42_PLUGIN_STRUCT
#undef X42_PLUGIN_STRUCT
#endif
#define X42_PLUGIN_STRUCT _plugin_surmeter
